n, m = map(int, input().split())
a = list(set(list(int(i) for i in input().split())))
b = list(set(list(int(i) for i in input().split())))
union = sorted(set(a) & set(b))
aNotB = sorted(set(a) - set(b))
bNotA = sorted(set(b) - set(a))
print(*union)
print(*aNotB)
print(*bNotA)